/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AionBlocks {
    'duration': number;
    'gqlUrl': string;
    'limit': number;
  }
  interface AionBlocksAttributes extends StencilHTMLAttributes {
    'duration'?: number;
    'gqlUrl'?: string;
    'limit'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AionBlocks': Components.AionBlocks;
  }

  interface StencilIntrinsicElements {
    'aion-blocks': Components.AionBlocksAttributes;
  }


  interface HTMLAionBlocksElement extends Components.AionBlocks, HTMLStencilElement {}
  var HTMLAionBlocksElement: {
    prototype: HTMLAionBlocksElement;
    new (): HTMLAionBlocksElement;
  };

  interface HTMLElementTagNameMap {
    'aion-blocks': HTMLAionBlocksElement
  }

  interface ElementTagNameMap {
    'aion-blocks': HTMLAionBlocksElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
